import { QRCodeSVG } from "qrcode.react";
import type { PaymentMethod } from "@/types";
import { formatCurrency } from "@/lib/format";
import { getDefaultPaymentSettings, type PaymentSettings } from "@/services/paymentSettingsService";
import { useEffect, useState } from "react";

interface PaymentQRProps {
  paymentMethod: PaymentMethod;
  amount: number;
  orderCode?: string;
  bankAccount?: string;
  bankName?: string;
  accountName?: string;
}

/**
 * Component to display QR code for payment methods
 * Supports VietQR, Bank Transfer, and E-wallet payments
 */
export function PaymentQR({
  paymentMethod,
  amount,
  orderCode,
  bankAccount: propBankAccount,
  bankName: propBankName,
  accountName: propAccountName,
}: PaymentQRProps) {
  const [settings, setSettings] = useState<PaymentSettings | null>(null);
  const [loading, setLoading] = useState(true);

  /**
   * Load payment settings from API
   */
  useEffect(() => {
    const loadSettings = async () => {
      try {
        setLoading(true);
        const defaultSettings = await getDefaultPaymentSettings(paymentMethod);
        setSettings(defaultSettings);
      } catch (error) {
        console.error("Error loading payment settings:", error);
      } finally {
        setLoading(false);
      }
    };

    if (paymentMethod !== "Cash") {
      loadSettings();
    } else {
      setLoading(false);
    }
  }, [paymentMethod]);

  /**
   * Use props if provided, otherwise use settings from API
   */
  const bankAccount = propBankAccount || settings?.accountNumber || settings?.phoneNumber || "";
  const bankName = propBankName || settings?.bankName || "";
  const accountName = propAccountName || settings?.accountName || "";
  /**
   * Generate VietQR string format
   * VietQR format: https://vietqr.io/format
   * Format: bank_account|amount|content
   */
  const generateVietQRString = (): string => {
    const content = orderCode ? `Thanh toan don ${orderCode}` : `Thanh toan ${formatCurrency(amount)}`;
    // VietQR format: bank_account|amount|content
    // For demo, we'll use a simplified format
    return `${bankAccount}|${Math.round(amount)}|${content}`;
  };

  /**
   * Generate Bank Transfer QR string
   * Contains bank account information and amount
   */
  const generateBankTransferString = (): string => {
    return `STB|${bankAccount}|${accountName}|${Math.round(amount)}|${orderCode || ""}`;
  };

  /**
   * Generate E-wallet QR string (Momo/ZaloPay)
   * Contains payment link or account info
   */
  const generateEwalletString = (): string => {
    // For Momo/ZaloPay, we can use a payment link format
    // In production, this would be generated by the payment gateway
    return `momo://transfer?phone=${bankAccount}&amount=${Math.round(amount)}&note=${orderCode || "Payment"}`;
  };

  /**
   * Get QR code value based on payment method
   */
  const getQRValue = (): string => {
    switch (paymentMethod) {
      case "VietQR":
        return generateVietQRString();
      case "BankTransfer":
        return generateBankTransferString();
      case "Momo":
      case "ZaloPay":
        return generateEwalletString();
      default:
        return "";
    }
  };

  /**
   * Get payment method display name
   */
  const getPaymentMethodName = (): string => {
    switch (paymentMethod) {
      case "VietQR":
        return "VietQR";
      case "BankTransfer":
        return "Chuyển khoản";
      case "Momo":
        return "Ví MoMo";
      case "ZaloPay":
        return "Ví ZaloPay";
      default:
        return "";
    }
  };

  /**
   * Get payment instructions based on method
   */
  const getPaymentInstructions = (): string => {
    switch (paymentMethod) {
      case "VietQR":
        return "Quét mã QR bằng ứng dụng ngân hàng để thanh toán";
      case "BankTransfer":
        return `Chuyển khoản đến:\n${bankName}\nSTK: ${bankAccount}\nTên: ${accountName}`;
      case "Momo":
        return "Quét mã QR bằng ứng dụng MoMo để thanh toán";
      case "ZaloPay":
        return "Quét mã QR bằng ứng dụng ZaloPay để thanh toán";
      default:
        return "";
    }
  };

  const qrValue = getQRValue();

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center space-y-4 p-6">
        <div className="text-center">Đang tải thông tin thanh toán...</div>
      </div>
    );
  }

  if (!qrValue || (!bankAccount && paymentMethod !== "Cash")) {
    return (
      <div className="flex flex-col items-center justify-center space-y-4 p-6">
        <div className="text-center text-muted-foreground">
          <p>Chưa cấu hình thông tin thanh toán</p>
          <p className="text-sm mt-2">Vui lòng cấu hình trong Settings</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center space-y-4 p-6">
      <div className="text-center space-y-2">
        <h3 className="text-lg font-semibold">Thanh toán qua {getPaymentMethodName()}</h3>
        <p className="text-2xl font-bold text-primary">{formatCurrency(amount)}</p>
        {orderCode && (
          <p className="text-sm text-muted-foreground">Mã đơn: {orderCode}</p>
        )}
      </div>

      <div className="bg-white p-4 rounded-lg border-2 border-primary/20">
        <QRCodeSVG
          value={qrValue}
          size={256}
          level="H"
          includeMargin={true}
        />
      </div>

      {(paymentMethod === "BankTransfer") && (
        <div className="text-center space-y-1 text-sm bg-muted p-4 rounded-lg w-full">
          <p className="font-medium">{bankName}</p>
          <p>Số tài khoản: <span className="font-mono font-semibold">{bankAccount}</span></p>
          <p>Chủ tài khoản: <span className="font-semibold">{accountName}</span></p>
          <p className="text-muted-foreground mt-2">Số tiền: {formatCurrency(amount)}</p>
        </div>
      )}

      <p className="text-sm text-center text-muted-foreground max-w-xs">
        {getPaymentInstructions()}
      </p>

      <div className="text-xs text-center text-muted-foreground">
        Vui lòng xác nhận sau khi thanh toán thành công
      </div>
    </div>
  );
}

